### ISSUE TITLE
Menus e HUD do personagem

### ISSUE THREAD

**Issue by booleangabs** [booleangabs/Projeto-IP-2020.1#6]

**Comment by bruhenri12** [comment]
Design do menu inicial - sem background - produzido no GIMP.
Arquivo contendo:
- o .xcf (GIMP)
- imagens dos botões de Novo Jogo e Continuar
- paleta de cores
[Menu.zip](https://github.com/booleangabs/Projeto-IP-2020.1/files/6333807/Menu.zip)

**Comment by booleangabs** [comment]
HUD básica adicionada. Possibilidade de adicão de ícones e estilização caso haja tempo
